version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.3
    container_name: filebeat
    depends_on:
      - elasticsearch
    volumes:
      - /home/juan/composetest/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /home/juan/composetest/logs:/usr/share/filebeat/logs
    environment:
      - ELASTIC_HOSTS=https://elasticsearch:9200
