filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.json
  fields:
    index: "dummy"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "%{[fields.index]}"

setup.template.name: "app"
setup.template.pattern: "app-*"